name: Security Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Chạy hàng tuần vào thứ 2 lúc 9:00 UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Check for known vulnerabilities
      run: npm audit --audit-level high
      
    - name: Update dependencies
      if: github.event_name == 'schedule'
      run: |
        npm update
        npm audit fix
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package*.json
        git commit -m "chore: update dependencies" || echo "No updates needed"
        git push || echo "No changes to push" 